networks:
  local:
    name: local
    driver: bridge

services:
  dotnet-rpg-api:
    image: dotnet-rpg
    container_name: dotnet-rpg-api
    build:
      context: .
      dockerfile: apps/api/DotNetRPG.API/Dockerfile
    ports:
      - "5001:5001"
    environment:
      - ASPNETCORE_URLS=http://+:5001
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=${CONNECTION_STRING}  